SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS email_verifications;
DROP TABLE IF EXISTS login_attempts;
DROP TABLE IF EXISTS denuncias;
DROP TABLE IF EXISTS user_scores;
DROP TABLE IF EXISTS avaliacoes;
DROP TABLE IF EXISTS mensagens;
DROP TABLE IF EXISTS propostas;
DROP TABLE IF EXISTS anuncios;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;
